version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: pgvector_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    mem_limit: 512m # Limit memory to 512 MB

volumes:
  postgres_data1:
